import { Github, Mail, Twitter } from "lucide-react";

export const productLinks = [
  { label: "Explore", path: "/explore" },
  { label: "Pricing", path: "/pricing" },
  { label: "Documentation", path: "/docs" },
];

export const companyLinks = [
  { label: "About", path: "/about" },
  { label: "Contact", path: "/contact" },
  { label: "Privacy", path: "/privacy" },
  { label: "Terms", path: "/terms" },
];

export const connectLinks = [
  { icon: Github, href: "https://github.com/repovitals" },
  {
    icon: Twitter,
    href: "https://twitter.com/intent/follow?screen_name=repovitals",
  },
  { icon: Mail, href: "mailto:support@repovitals.com" },
];

export const repoDataExport = {
  description:
    "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
  language: "JavaScript",
  stars: 218000,
  forks: 45200,
  lastUpdated: "2 hours ago",
  overallScore: 9.2,
  scores: {
    security: 8.7,
    maintenance: 9.5,
    popularity: 9.8,
  },
  badges: ["Maintained", "Security Scan", "Popular"],
  scorecardData: {
    lastScan: "2024-01-15",
    checks: [
      {
        name: "Binary-Artifacts",
        score: 10,
        description: "No binary artifacts found",
      },
      {
        name: "Branch-Protection",
        score: 8,
        description: "Branch protection enabled with some gaps",
      },
      {
        name: "CI-Tests",
        score: 10,
        description: "CI tests run on all changes",
      },
      { name: "Code-Review", score: 9, description: "Most changes reviewed" },
      {
        name: "Contributors",
        score: 10,
        description: "Multiple contributors from different organizations",
      },
      {
        name: "Dangerous-Workflow",
        score: 10,
        description: "No dangerous workflow patterns detected",
      },
      {
        name: "Dependency-Update-Tool",
        score: 8,
        description: "Automated dependency updates configured",
      },
      { name: "Fuzzing", score: 0, description: "No fuzzing tools detected" },
      { name: "License", score: 10, description: "License file present" },
      {
        name: "Maintained",
        score: 10,
        description: "Recent activity and maintenance",
      },
      {
        name: "Packaging",
        score: 10,
        description: "Proper packaging configuration",
      },
      {
        name: "Pinned-Dependencies",
        score: 7,
        description: "Most dependencies pinned",
      },
      {
        name: "SAST",
        score: 5,
        description: "Some static analysis tools detected",
      },
      {
        name: "Security-Policy",
        score: 10,
        description: "Security policy documented",
      },
      {
        name: "Signed-Releases",
        score: 0,
        description: "Releases not signed",
      },
      {
        name: "Token-Permissions",
        score: 8,
        description: "GitHub tokens have appropriate permissions",
      },
      {
        name: "Vulnerabilities",
        score: 10,
        description: "No known vulnerabilities",
      },
      {
        name: "Webhooks",
        score: 9,
        description: "Webhooks properly configured",
      },
    ],
  },
  contributors: [
    {
      name: "Dan Abramov",
      contributions: 1247,
      avatar:
        "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
    },
    {
      name: "Sebastian Markbåge",
      contributions: 892,
      avatar:
        "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
    },
    {
      name: "Andrew Clark",
      contributions: 756,
      avatar:
        "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
    },
    {
      name: "Brian Vaughn",
      contributions: 623,
      avatar:
        "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
    },
  ],
  dependencies: {
    total: 127,
    outdated: 8,
    vulnerable: 2,
    recent: [
      {
        name: "typescript",
        version: "5.1.6",
        latest: "5.2.2",
        status: "outdated",
      },
      {
        name: "eslint",
        version: "8.45.0",
        latest: "8.45.0",
        status: "current",
      },
      {
        name: "react-dom",
        version: "18.2.0",
        latest: "18.2.0",
        status: "current",
      },
      {
        name: "webpack",
        version: "5.88.1",
        latest: "5.88.2",
        status: "outdated",
      },
    ],
  },
  activity: [
    {
      type: "commit",
      message: "Fix concurrent mode rendering issue",
      author: "Dan Abramov",
      time: "2 hours ago",
    },
    {
      type: "release",
      message: "Release v18.2.1",
      author: "React Team",
      time: "1 day ago",
    },
    {
      type: "issue",
      message: "Performance improvement for large lists",
      author: "Community",
      time: "2 days ago",
    },
    {
      type: "pr",
      message: "Add support for React DevTools",
      author: "Brian Vaughn",
      time: "3 days ago",
    },
  ],
};


export   const repositories = [
    {
      id: 1,
      owner: 'facebook',
      name: 'react',
      description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
      language: 'JavaScript',
      stars: 218000,
      forks: 45200,
      score: 9.2,
      security: 8.7,
      maintenance: 9.5,
      popularity: 9.8,
      category: 'Web Framework',
      license: 'MIT',
      lastUpdated: '2 hours ago',
      badges: ['maintained', 'secure', 'popular'],
      hasFullData: true
    },
    {
      id: 2,
      owner: 'microsoft',
      name: 'vscode',
      description: 'Visual Studio Code - Open Source ("Code - OSS")',
      language: 'TypeScript',
      stars: 156000,
      forks: 27800,
      score: 8.9,
      security: 9.1,
      maintenance: 8.8,
      popularity: 8.7,
      category: 'Developer Tool',
      license: 'MIT',
      lastUpdated: '4 hours ago',
      badges: ['maintained', 'secure', 'popular'],
      hasFullData: true
    },
    {
      id: 3,
      owner: 'nodejs',
      name: 'node',
      description: 'Node.js JavaScript runtime',
      language: 'JavaScript',
      stars: 102000,
      forks: 28100,
      score: 8.5,
      security: 8.2,
      maintenance: 8.9,
      popularity: 8.4,
      category: 'Runtime',
      license: 'MIT',
      lastUpdated: '6 hours ago',
      badges: ['maintained', 'secure'],
      hasFullData: true
    },
    {
      id: 4,
      owner: 'tensorflow',
      name: 'tensorflow',
      description: 'An Open Source Machine Learning Framework for Everyone',
      language: 'Python',
      stars: 182000,
      forks: 74200,
      score: 8.1,
      security: 7.8,
      maintenance: 8.6,
      popularity: 7.9,
      category: 'AI/ML',
      license: 'Apache-2.0',
      lastUpdated: '1 day ago',
      badges: ['maintained', 'popular'],
      hasFullData: false
    },
    {
      id: 5,
      owner: 'vercel',
      name: 'next.js',
      description: 'The React Framework for the Web',
      language: 'JavaScript',
      stars: 118000,
      forks: 25300,
      score: 9.0,
      security: 8.9,
      maintenance: 9.2,
      popularity: 8.9,
      category: 'Web Framework',
      license: 'MIT',
      lastUpdated: '3 hours ago',
      badges: ['maintained', 'secure', 'popular'],
      hasFullData: true
    },
    {
      id: 6,
      owner: 'vuejs',
      name: 'vue',
      description: 'Vue.js is a progressive, incrementally-adoptable JavaScript framework',
      language: 'TypeScript',
      stars: 206000,
      forks: 33700,
      score: 8.7,
      security: 8.4,
      maintenance: 9.1,
      popularity: 8.6,
      category: 'Web Framework',
      license: 'MIT',
      lastUpdated: '5 hours ago',
      badges: ['maintained', 'secure', 'popular'],
      hasFullData: true
    },
    {
        id: 7,
        owner: 'lodash',
        name: 'lodash',
        description: 'A modern JavaScript utility library delivering modularity, performance & extras.',
        language: 'JavaScript',
        stars: 57000,
        forks: 7000,
        score: 4.8,
        security: 3.9,
        maintenance: 5.1,
        popularity: 6.3,
        category: 'Utility Library',
        license: 'MIT',
        lastUpdated: '2 weeks ago',
        badges: [],
        hasFullData: true
      },
      {
        id: 8,
        owner: 'pallets',
        name: 'flask',
        description: 'A micro web framework written in Python.',
        language: 'Python',
        stars: 65000,
        forks: 16000,
        score: 7.5,
        security: 6.7,
        maintenance: 8.2,
        popularity: 7.6,
        category: 'Web Framework',
        license: 'BSD-3-Clause',
        lastUpdated: '5 days ago',
        badges: ['maintained', 'popular'],
        hasFullData: true
      },
      {
        id: 9,
        owner: 'facebook',
        name: 'react',
        description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
        language: 'JavaScript',
        stars: 212000,
        forks: 45000,
        score: 9.2,
        security: 9.0,
        maintenance: 9.4,
        popularity: 9.5,
        category: 'UI Library',
        license: 'MIT',
        lastUpdated: '12 hours ago',
        badges: ['maintained', 'secure', 'popular'],
        hasFullData: true
      },
      {
        id: 10,
        owner: 'python',
        name: 'cpython',
        description: 'The Python programming language.',
        language: 'C',
        stars: 58000,
        forks: 27000,
        score: 7.1,
        security: 7.5,
        maintenance: 6.2,
        popularity: 7.8,
        category: 'Programming Language',
        license: 'Python-2.0',
        lastUpdated: '1 day ago',
        badges: ['popular'],
        hasFullData: true
      },
      {
        id: 11,
        owner: 'getify',
        name: 'You-Dont-Know-JS',
        description: 'A book series on JavaScript.',
        language: 'JavaScript',
        stars: 170000,
        forks: 34000,
        score: 4.5,
        security: 4.2,
        maintenance: 3.9,
        popularity: 7.2,
        category: 'Educational',
        license: 'CC-BY-NC-ND-4.0',
        lastUpdated: '1 month ago',
        badges: [],
        hasFullData: true
      }
  ];